### ISSUE TITLE
Upgrade to Webpack 5

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-dev-meta#25]
Webpack 4 doesn't run on Node 17, which is a problem because this is the next LTS and some users run this as their main environment.

Also, Webpack 4 has a lot of dependencies that's not really required because the Node version requirement of OS.js is 12, which could be bumped to 14 without any impact.

So this will fix any issues related to webpack 4 and bring on some nice speed improvements both in build times and dependency installation.

---

Split out from:

* https://github.com/os-js/OS.js/issues/785

Related:

* https://github.com/os-js/osjs-dev-meta/pull/26
* https://github.com/os-js/osjs-client/tree/feat/webpack-5

### Stage 1

> Steps should probably be done with Node 16 or earlier.

> Pretty much the same procedure as done in https://github.com/os-js/osjs-dev-meta/issues/24

* [x] Upgrade Webpack
* [x] Upgrade loaders and extensions (and replace any defunct stuff)
* [x] Make this work on the client repo (`osjs-client`)
* [ ] Then ensure this works on the base repo (`OS.js`)
* [ ] Release as major version bump

### Stage 2

This stage could probably be automated since anything in stage 1 will apply project-wide.

* [ ] Go through all packages using `dev-meta`, upgrade, test, release.

**Comment by frank-dspeed** [comment]
Please Stop that effort switch to rollup to reduce future migrations in future.
